sudo: false
language: node_js
cache: false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - echo "test"
  on:
    branch: deploy
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $MACHINE_USERNAME@$MACHINE_ADDRESS pwd
after_success:
- pwd
- ls -al
- npm ci && npm run build
- ls -al
